title: digits
description: A product of my software engineering skills cultivated through my ICS314 software engineering course.
google_analytics:
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions